# timeout
timeout = "1200s"
# your website url
#baseURL = 'https://github.com/EvanLih/evanlih.github.io'

#test dynamic baseurl
baseURL = "/"
relativeURLS = true

# website title
title = 'Evan'
# don't touch this
disableKinds = ["section", "taxonomy", "term", "home"]
# robots.txt
enableRobotsTXT = true
# available options
# * en (powered by Geist)
# * de (powered by Geist)
# * es (powered by Geist)
# * fr (powered by Geist)
# * it (powered by Geist)
# * zh-sg zh-cn (powered by Noto Sans SC)
# * zh-hk zh-tw zh-mo (powered by Noto Sans TC)
# * ja (powered by Noto Sans JP)
# * ko (powered by Noto Sans KR)
defaultContentLanguage = 'en'


# theme as a module
[module]
#replacements = "github.com/Sped0n/bridget/v2 -> ../.."
[[module.imports]]
  path = "github.com/Sped0n/bridget/v2"
  # bridget 
 